<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification" Version="9.3.1" />
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ADOPZ.DataAccess\ADOPZ.DataAccess.csproj" />
    <ProjectReference Include="..\ADOPZ.Entities\ADOPZ.Entities.csproj" />
    <ProjectReference Include="..\Boutiquemoda.DataAccess\ADOPZ.DataAccess.csproj" />
    <ProjectReference Include="..\BoutiqueModa.Entities\ADOPZ.Entities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UseCases\Brands\Commands\Createcommand\" />
    <Folder Include="UseCases\Brands\Queries\" />
    <Folder Include="UseCases\Products\Commands\" />
    <Folder Include="UseCases\Products\Specifications\" />
    <Folder Include="UseCases\Products\Queries\" />
    <Folder Include="UseCases\Quotations\Commands\" />
    <Folder Include="UseCases\Quotations\Specifications\" />
    <Folder Include="UseCases\Quotations\Queries\" />
    <Folder Include="UseCases\User\Commands\" />
    <Folder Include="UseCases\User\Specifications\" />
    <Folder Include="UseCases\User\Queries\" />
  </ItemGroup>

</Project>
